export const MENU_ITEMS = [
    {
      key: 'navigation',
      label: 'Navigation',
      isTitle: true,
    },
    {
      key: 'dashboards',
      label: 'Dashboards',
      isTitle: false,
      icon: 'uil-home-alt',
      badge: { variant: 'success', text: '5' },
      children: [
        {
          key: 'ds-analytics',
          label: 'Analytics',
          url: '/dashboard/analytics',
          parentKey: 'dashboards',
        },
        {
          key: 'ds-ecommerce',
          label: 'Ecommerce',
          url: '/dashboard/ecommerce',
          parentKey: 'dashboards',
        },
        {
          key: 'ds-project',
          label: 'Projects',
          url: '/dashboard/project',
          parentKey: 'dashboards',
        },
        {
          key: 'ds-crm',
          label: 'CRM',
          url: '/dashboard/crm',
          parentKey: 'dashboards',
        },
        {
          key: 'ds-ewallet',
          label: 'E-Wallet',
          url: '/dashboard/e-wallet',
          parentKey: 'dashboards',
        },
      ],
    },
    {
      key: 'apps',
      label: 'Apps',
      isTitle: true,
    },
    {
      key: 'apps-calendar',
      label: 'Calendar',
      isTitle: false,
      icon: 'uil-calender',
      url: '/apps/calendar',
    },
    {
      key: 'apps-chat',
      label: 'Chat',
      isTitle: false,
      icon: 'uil-comments-alt',
      url: '/apps/chat',
    },
    {
      key: 'apps-crm',
      label: 'CRM',
      isTitle: false,
      badge: { variant: 'danger', text: 'New' },
      icon: 'uil-tachometer-fast',
      children: [
        {
          key: 'crm-projects',
          label: 'Projects',
          url: '/apps/crm/projects',
          parentKey: 'apps-crm',
        },
        {
          key: 'crm-orders',
          label: 'Orders List',
          url: '/apps/crm/orders',
          parentKey: 'apps-crm',
        },
        {
          key: 'crm-clients',
          label: 'Clients',
          url: '/apps/crm/clients',
          parentKey: 'apps-crm',
        },
        {
          key: 'crm-management',
          label: 'Management',
          url: '/apps/crm/management',
          parentKey: 'apps-crm',
        },
      ],
    },
    {
      key: 'apps-ecommerce',
      label: 'Ecommerce',
      isTitle: false,
      icon: 'uil-store',
      children: [
        {
          key: 'ecommerce-products',
          label: 'Products',
          url: '/apps/ecommerce/products',
          parentKey: 'apps-ecommerce',
        },
        {
          key: 'ecommerce-details',
          label: 'Products Details',
          url: '/apps/ecommerce/product-details',
          parentKey: 'apps-ecommerce',
        },
        {
          key: 'ecommerce-orders',
          label: 'Orders',
          url: '/apps/ecommerce/orders',
          parentKey: 'apps-ecommerce',
        },
        {
          key: 'ecommerce-order-details',
          label: 'Order Details',
          url: '/apps/ecommerce/order-details',
          parentKey: 'apps-ecommerce',
        },
        {
          key: 'ecommerce-customers',
          label: 'Customers',
          url: '/apps/ecommerce/customers',
          parentKey: 'apps-ecommerce',
        },
        {
          key: 'ecommerce-shopping-cart',
          label: 'Shopping Cart',
          url: '/apps/ecommerce/shopping-cart',
          parentKey: 'apps-ecommerce',
        },
        {
          key: 'ecommerce-checkout',
          label: 'Checkout',
          url: '/apps/ecommerce/checkout',
          parentKey: 'apps-ecommerce',
        },
        {
          key: 'ecommerce-sellers',
          label: 'Sellers',
          url: '/apps/ecommerce/sellers',
          parentKey: 'apps-ecommerce',
        },
      ],
    },
    {
      key: 'apps-email',
      label: 'Email',
      isTitle: false,
      icon: 'uil-envelope',
      children: [
        {
          key: 'email-inbox',
          label: 'Inbox',
          url: '/apps/email/inbox',
          parentKey: 'apps-email',
        },
        {
          key: 'email-read-email',
          label: 'Read Email',
          url: '/apps/email/read',
          parentKey: 'apps-email',
        },
      ],
    },
    {
      key: 'apps-projects',
      label: 'Projects',
      isTitle: false,
      icon: 'uil-briefcase',
      children: [
        {
          key: 'project-list',
          label: 'List',
          url: '/apps/projects/list',
          parentKey: 'apps-projects',
        },
        {
          key: 'project-details',
          label: 'Details',
          url: '/apps/projects/details',
          parentKey: 'apps-projects',
        },
        {
          key: 'project-gantt',
          label: 'Gantt',
          url: '/apps/projects/gantt',
          badge: { variant: 'light', text: 'New' },
          parentKey: 'apps-projects',
        },
        {
          key: 'project-create-project',
          label: 'Create Project',
          url: '/apps/projects/create',
          parentKey: 'apps-projects',
        },
      ],
    },
    {
      key: 'apps-social',
      label: 'Social Feed',
      isTitle: false,
      icon: 'uil-rss',
      url: '/apps/social',
    },
    {
      key: 'apps-tasks',
      label: 'Tasks',
      isTitle: false,
      icon: 'uil-clipboard-alt',
      children: [
        {
          key: 'task-list',
          label: 'List',
          url: '/apps/tasks/list',
          parentKey: 'apps-tasks',
        },
        {
          key: 'task-details',
          label: 'Details',
          url: '/apps/tasks/details',
          parentKey: 'apps-tasks',
        },
        {
          key: 'task-kanban',
          label: 'Kanban Board',
          url: '/apps/tasks/kanban',
          parentKey: 'apps-tasks',
        },
      ],
    },
    {
      key: 'apps-file-manager',
      label: 'File Manager',
      isTitle: false,
      icon: 'uil-folder-plus',
      url: '/apps/file',
    }
]